apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catest.fullname" . }}-cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  {{- include "catest.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.clusterAutoscaler.serviceAccount.annotations | nindent 4 }}